services:
  - type: web
    name: chinese-poker
    env: node
    buildCommand: |
      npm install
      node build-client.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: CI
        value: "false"
    plan: free
    healthCheckPath: /api/health 